POST http://localhost:8000/quotes/request
Content-Type: application/json

{
  "moveType": "HOME_MOVE",
  "moveDate": "2025-03-23T15:00:00.000Z",
  "moveFrom": "경기 가평군 청평면 여울길 3",
  "moveTo": "부산 부산진구 경마장로 1"
}

# {
#   "이사종류": "소형이사 (원룸, 투룸, 20평대 미만)",
#   "이사예정일": "2025년 3월 24일",
#   "이사예정시간": "오전 12시 00분",
#   "이사지역 출발지": "울산 중구 만남의거리 1",
#   "이사지역 도착지": "부산 부산진구 경마장로 1"
# }
###
GET http://localhost:8000/quotes/all




###

GET http://localhost:8000/test 

###

GET http://localhost:8000/